### ISSUE TITLE
Remove 'ssh' binary from source and possibly from package

### ISSUE THREAD

**Issue by djmitche** [bartmatthaei/sshkeychain#2]
Right now, there's an 'ssh' binary in the repo.  This may have licensing implications.  Eric says it was for Panther compatibility.  Maybe we need to give up Panther compatibility?

From Eric:

My personal option would be for either dropping panther support or
building openssh libs right in the main package.  Either would solve
the problem.

**Comment by dmzimmerman** [comment]
Assuming the ssh is OpenSSH (it'd pretty much have to be), it's under the BSD license (or less restrictive licenses for some components), and there are therefore no licensing implications except for having to put the relevant text in the documentation somewhere.

That having been said, dropping Panther support doesn't seem like a bad idea.

**Comment by djmitche** [comment]
From the mailing list, let's hang onto it for the time being, but not use it in OS X >= 10.4.
